### ISSUE TITLE
Make tests more customizable

### ISSUE THREAD

**Issue by cgccuser** [Vyxal/Vyxal#498]
Right now, tests are restricted to giving inputs as literals and only checking for equality. We need to be able to do custom comparison and add input by evaluating Vyxal first. I propose adding this form of tests:
```yaml
tests:
  - "[[1, 3], 2] : 'foo'" # normal test
  - inputs: [[1, 3], 2]
    header: +→x3↑ # Some random Vyxal code to be executed before the element itself
    check: "'foo' in res" # Python code with more flexible checking (res would be the variable the result is assigned to)
```
