### ISSUE TITLE
Adding new digraph to process date and time

### ISSUE THREAD

**Issue by edison1119** [Vyxal/Vyxal#554]
we can add a new digraph which allows:

- treat a string as date/time
- add/subtract date/time
- advance date/time by 1 unit
- multiply/divide date/time by a number
- seperate date/time into ints
- merge get current date command into this digraph

**Comment by razetime** [comment]
do you want a single builtin with multiple modes, or a digraph for each of these functionalities?

**Comment by cgccuser** [comment]
I think separate digraphs would be good

**Comment by Lyxal** [comment]
Proposed digraphs:

```yaml
- element: "¨+"
  name: Add Date and Time
  description: Add a certain amount of time to a date
  arity: 2
  overloads:
    num-num: from_unix_timestamp(lhs) + rhs # rhs = seconds to add
    num-str: from_unix_timestamp(lhs) + seconds(from_iso_format(rhs))
    str-num: from_iso_format(lhs) + seconds(from_unix_timestamp(rhs))
    str-str: from_iso_format(lhs) + seconds(from_iso_format(rhs))
  vectorise: true
```
