### ISSUE TITLE
Increment/Decrement until false

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#766]
Diagraphs for `Increment until false`, as well as `Decrement until false`. We could use `∆›` and `∆‹`, respectively.

```
- element: "∆›"
  name: Increment until false
  description: Increment a until b(a) is false
  arity: 2
  overloads:
    any-fun: while b(a): a += 1
    fun-any: while a(b): b += 1
  vectorise: false
```

```
- element: "∆‹"
  name: Decrement until false
  description: Decrement a until b(a) is false
  arity: 2
  overloads:
    any-fun: while b(a): a -= 1
    fun-any: while a(b): b -= 1
  vectorise: false
```
