### ISSUE TITLE
All multiples diagraph

### ISSUE THREAD

**Issue by AMiller42** [Vyxal/Vyxal#767]
Diagraph returning an infinite LazyList of multiples of a number `a`.

```
- element: TBD
  name: All Multiples
  description: Return all multiples of a
  arity: 1
  overloads:
    num: [a*1, a*2, a*3, a*4, ...]
  vectorise: true
```
